name: OK Check / Progress Push PPC

on:
  workflow_dispatch: 
    branches:
      - main
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run Make (OK)
      run: |
        dkp-pacman -Syu wiiu-dev wiiu-portlibs --noconfirm
        make -j$(nproc)
        echo "done use elf-rpx converter.exe on windows to get a rpx, no wuhb for now"
    - uses: actions/upload-artifact@master
      with:
        name: game
        path: .
