name: OK Check / Progress Push PPC

on:
  workflow_dispatch: 
    branches:
      - main
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run Make (OK)
      run: make -j$(nproc)
    - uses: actions/upload-artifact@master
      with:
        name: game
        path: build
